FROM java
COPY /var/jenkins/workspace/property-management/target/property-management-1.0.0.jar /
COPY /var/jenkins/workspace/property-management/config /
ENTRYPOINT java -jar property-management-1.0.0